use_frameworks!

platform :ios, '8.0'

target 'AJKit_Example' do
  pod 'AJKit',
  :subspecs => ['Foundation', 'UIKit', 'Runtime', 'Algorithm'],
  :path => '../'

  target 'AJKit_Tests' do
    inherit! :search_paths

    
  end
end
